// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcblyTc4HXQv7KXRYLK3fHbHPc9sNU3Vg',
    appId: '1:795536206416:web:7d568f72d0cacf511eff55',
    messagingSenderId: '795536206416',
    projectId: 'farm2home-59d16',
    authDomain: 'farm2home-59d16.firebaseapp.com',
    storageBucket: 'farm2home-59d16.firebasestorage.app',
    measurementId: 'G-JCT1VF4E2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjzlDaxpZ2vis22KZZlntcyPcTt-HBU98',
    appId: '1:795536206416:android:b10c5908099fbec21eff55',
    messagingSenderId: '795536206416',
    projectId: 'farm2home-59d16',
    storageBucket: 'farm2home-59d16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPip-TiH6S_Ex5ewYcdLDv0az6BnygW0s',
    appId: '1:795536206416:ios:d76baac9af13ab331eff55',
    messagingSenderId: '795536206416',
    projectId: 'farm2home-59d16',
    storageBucket: 'farm2home-59d16.firebasestorage.app',
    iosClientId: '795536206416-j2p7jsr4kgsobkoec2i2albg2gsiloqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.farm2homeDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPip-TiH6S_Ex5ewYcdLDv0az6BnygW0s',
    appId: '1:795536206416:ios:d76baac9af13ab331eff55',
    messagingSenderId: '795536206416',
    projectId: 'farm2home-59d16',
    storageBucket: 'farm2home-59d16.firebasestorage.app',
    iosClientId: '795536206416-j2p7jsr4kgsobkoec2i2albg2gsiloqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.farm2homeDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM2xQbORe_fyzaDJSQ_BL3baLyX522yNo',
    appId: '1:795536206416:web:6a05047f989105491eff55',
    messagingSenderId: '795536206416',
    projectId: 'farm2home-59d16',
    authDomain: 'farm2home-59d16.firebaseapp.com',
    storageBucket: 'farm2home-59d16.firebasestorage.app',
    measurementId: 'G-R6TG600YJK',
  );
}
