/// Product model for Farm2Home app
class Product {
  final String id;
  final String name;
  final String description;
  final double price;
  final String unit;
  final String category;
  final String imageIcon;

  Product({
    required this.id,
    required this.name,
    required this.description,
    required this.price,
    required this.unit,
    required this.category,
    required this.imageIcon,
  });
}

/// Sample products data - Comprehensive vegetable and produce list
final List<Product> sampleProducts = [
  // Leafy Greens
  Product(
    id: '1',
    name: 'Green Lettuce',
    description: 'Crisp and fresh lettuce heads',
    price: 2.49,
    unit: 'per head',
    category: 'Vegetables',
    imageIcon: '🥬',
  ),
  Product(
    id: '2',
    name: 'Spinach',
    description: 'Fresh baby spinach leaves',
    price: 3.49,
    unit: 'per bunch',
    category: 'Vegetables',
    imageIcon: '🥬',
  ),
  Product(
    id: '3',
    name: 'Kale',
    description: 'Organic curly kale',
    price: 2.99,
    unit: 'per bunch',
    category: 'Vegetables',
    imageIcon: '🥬',
  ),
  Product(
    id: '4',
    name: 'Cabbage',
    description: 'Fresh green cabbage',
    price: 2.29,
    unit: 'per head',
    category: 'Vegetables',
    imageIcon: '🥬',
  ),
  Product(
    id: '5',
    name: 'Bok Choy',
    description: 'Asian leafy vegetable',
    price: 2.79,
    unit: 'per bunch',
    category: 'Vegetables',
    imageIcon: '🥬',
  ),

  // Root Vegetables
  Product(
    id: '6',
    name: 'Carrots',
    description: 'Sweet, crunchy carrots',
    price: 2.99,
    unit: 'per bunch',
    category: 'Vegetables',
    imageIcon: '🥕',
  ),
  Product(
    id: '7',
    name: 'Potatoes',
    description: 'Fresh russet potatoes',
    price: 3.49,
    unit: 'per 5 lb bag',
    category: 'Vegetables',
    imageIcon: '🥔',
  ),
  Product(
    id: '8',
    name: 'Sweet Potatoes',
    description: 'Orange-fleshed sweet potatoes',
    price: 3.99,
    unit: 'per lb',
    category: 'Vegetables',
    imageIcon: '🍠',
  ),
  Product(
    id: '9',
    name: 'Beets',
    description: 'Fresh red beets',
    price: 2.79,
    unit: 'per bunch',
    category: 'Vegetables',
    imageIcon: '🥕',
  ),
  Product(
    id: '10',
    name: 'Radishes',
    description: 'Crisp red radishes',
    price: 1.99,
    unit: 'per bunch',
    category: 'Vegetables',
    imageIcon: '🥕',
  ),
  Product(
    id: '11',
    name: 'Turnips',
    description: 'Fresh white turnips',
    price: 2.49,
    unit: 'per bunch',
    category: 'Vegetables',
    imageIcon: '🥕',
  ),
  Product(
    id: '12',
    name: 'Onions',
    description: 'Yellow cooking onions',
    price: 2.99,
    unit: 'per 3 lb bag',
    category: 'Vegetables',
    imageIcon: '🧅',
  ),
  Product(
    id: '13',
    name: 'Garlic',
    description: 'Fresh garlic bulbs',
    price: 4.99,
    unit: 'per lb',
    category: 'Vegetables',
    imageIcon: '🧄',
  ),
  Product(
    id: '14',
    name: 'Ginger',
    description: 'Fresh ginger root',
    price: 5.99,
    unit: 'per lb',
    category: 'Vegetables',
    imageIcon: '🫚',
  ),

  // Fruiting Vegetables
  Product(
    id: '15',
    name: 'Fresh Tomatoes',
    description: 'Organic, locally grown tomatoes',
    price: 3.99,
    unit: 'per lb',
    category: 'Vegetables',
    imageIcon: '🍅',
  ),
  Product(
    id: '16',
    name: 'Cherry Tomatoes',
    description: 'Sweet cherry tomatoes',
    price: 4.49,
    unit: 'per pint',
    category: 'Vegetables',
    imageIcon: '🍅',
  ),
  Product(
    id: '17',
    name: 'Bell Peppers',
    description: 'Colorful bell peppers',
    price: 3.99,
    unit: 'per lb',
    category: 'Vegetables',
    imageIcon: '🫑',
  ),
  Product(
    id: '18',
    name: 'Cucumbers',
    description: 'Fresh crisp cucumbers',
    price: 1.99,
    unit: 'per lb',
    category: 'Vegetables',
    imageIcon: '🥒',
  ),
  Product(
    id: '19',
    name: 'Zucchini',
    description: 'Fresh green zucchini',
    price: 2.49,
    unit: 'per lb',
    category: 'Vegetables',
    imageIcon: '🥒',
  ),
  Product(
    id: '20',
    name: 'Eggplant',
    description: 'Dark purple eggplant',
    price: 3.49,
    unit: 'per lb',
    category: 'Vegetables',
    imageIcon: '🍆',
  ),
  Product(
    id: '21',
    name: 'Pumpkin',
    description: 'Fresh cooking pumpkin',
    price: 4.99,
    unit: 'per each',
    category: 'Vegetables',
    imageIcon: '🎃',
  ),
  Product(
    id: '22',
    name: 'Squash',
    description: 'Butternut squash',
    price: 3.49,
    unit: 'per lb',
    category: 'Vegetables',
    imageIcon: '🎃',
  ),

  // Cruciferous Vegetables
  Product(
    id: '23',
    name: 'Broccoli',
    description: 'Fresh green broccoli crowns',
    price: 3.49,
    unit: 'per head',
    category: 'Vegetables',
    imageIcon: '🥦',
  ),
  Product(
    id: '24',
    name: 'Cauliflower',
    description: 'Fresh white cauliflower',
    price: 3.99,
    unit: 'per head',
    category: 'Vegetables',
    imageIcon: '🥦',
  ),
  Product(
    id: '25',
    name: 'Brussels Sprouts',
    description: 'Fresh Brussels sprouts',
    price: 4.49,
    unit: 'per lb',
    category: 'Vegetables',
    imageIcon: '🥬',
  ),

  // Legumes
  Product(
    id: '26',
    name: 'Green Beans',
    description: 'Fresh snap beans',
    price: 3.99,
    unit: 'per lb',
    category: 'Vegetables',
    imageIcon: '🫘',
  ),
  Product(
    id: '27',
    name: 'Peas',
    description: 'Fresh sugar snap peas',
    price: 4.49,
    unit: 'per lb',
    category: 'Vegetables',
    imageIcon: '🫛',
  ),

  // Other Vegetables
  Product(
    id: '28',
    name: 'Celery',
    description: 'Fresh celery stalks',
    price: 2.49,
    unit: 'per bunch',
    category: 'Vegetables',
    imageIcon: '🥬',
  ),
  Product(
    id: '29',
    name: 'Asparagus',
    description: 'Fresh green asparagus',
    price: 5.99,
    unit: 'per bunch',
    category: 'Vegetables',
    imageIcon: '🥒',
  ),
  Product(
    id: '30',
    name: 'Corn',
    description: 'Sweet corn on the cob',
    price: 3.99,
    unit: 'per 6 ears',
    category: 'Vegetables',
    imageIcon: '🌽',
  ),
  Product(
    id: '31',
    name: 'Mushrooms',
    description: 'Fresh button mushrooms',
    price: 4.99,
    unit: 'per 8 oz',
    category: 'Vegetables',
    imageIcon: '🍄',
  ),
  Product(
    id: '32',
    name: 'Leeks',
    description: 'Fresh leeks',
    price: 3.49,
    unit: 'per bunch',
    category: 'Vegetables',
    imageIcon: '🧅',
  ),
  Product(
    id: '33',
    name: 'Parsnips',
    description: 'Fresh parsnips',
    price: 2.99,
    unit: 'per bunch',
    category: 'Vegetables',
    imageIcon: '🥕',
  ),

  // Herbs
  Product(
    id: '34',
    name: 'Fresh Basil',
    description: 'Fragrant basil leaves',
    price: 2.99,
    unit: 'per bunch',
    category: 'Herbs',
    imageIcon: '🌿',
  ),
  Product(
    id: '35',
    name: 'Fresh Cilantro',
    description: 'Fresh cilantro bunches',
    price: 1.99,
    unit: 'per bunch',
    category: 'Herbs',
    imageIcon: '🌿',
  ),
  Product(
    id: '36',
    name: 'Fresh Parsley',
    description: 'Flat-leaf parsley',
    price: 1.99,
    unit: 'per bunch',
    category: 'Herbs',
    imageIcon: '🌿',
  ),
  Product(
    id: '37',
    name: 'Fresh Mint',
    description: 'Aromatic mint leaves',
    price: 2.49,
    unit: 'per bunch',
    category: 'Herbs',
    imageIcon: '🌿',
  ),
  Product(
    id: '38',
    name: 'Fresh Rosemary',
    description: 'Fragrant rosemary sprigs',
    price: 2.99,
    unit: 'per bunch',
    category: 'Herbs',
    imageIcon: '🌿',
  ),
  Product(
    id: '39',
    name: 'Fresh Thyme',
    description: 'Fresh thyme sprigs',
    price: 2.99,
    unit: 'per bunch',
    category: 'Herbs',
    imageIcon: '🌿',
  ),
  Product(
    id: '40',
    name: 'Fresh Dill',
    description: 'Fresh dill weed',
    price: 2.49,
    unit: 'per bunch',
    category: 'Herbs',
    imageIcon: '🌿',
  ),

  // Fruits
  Product(
    id: '41',
    name: 'Fresh Apples',
    description: 'Red delicious apples',
    price: 4.99,
    unit: 'per lb',
    category: 'Fruits',
    imageIcon: '🍎',
  ),
  Product(
    id: '42',
    name: 'Bananas',
    description: 'Fresh yellow bananas',
    price: 2.99,
    unit: 'per lb',
    category: 'Fruits',
    imageIcon: '🍌',
  ),
  Product(
    id: '43',
    name: 'Oranges',
    description: 'Juicy navel oranges',
    price: 4.49,
    unit: 'per lb',
    category: 'Fruits',
    imageIcon: '🍊',
  ),
  Product(
    id: '44',
    name: 'Strawberries',
    description: 'Sweet, ripe strawberries',
    price: 5.99,
    unit: 'per basket',
    category: 'Fruits',
    imageIcon: '🍓',
  ),
  Product(
    id: '45',
    name: 'Blueberries',
    description: 'Fresh blueberries',
    price: 6.99,
    unit: 'per pint',
    category: 'Fruits',
    imageIcon: '🫐',
  ),
  Product(
    id: '46',
    name: 'Grapes',
    description: 'Seedless green grapes',
    price: 4.99,
    unit: 'per lb',
    category: 'Fruits',
    imageIcon: '🍇',
  ),
  Product(
    id: '47',
    name: 'Watermelon',
    description: 'Sweet watermelon',
    price: 6.99,
    unit: 'per each',
    category: 'Fruits',
    imageIcon: '🍉',
  ),
  Product(
    id: '48',
    name: 'Lemons',
    description: 'Fresh lemons',
    price: 3.99,
    unit: 'per lb',
    category: 'Fruits',
    imageIcon: '🍋',
  ),
  Product(
    id: '49',
    name: 'Limes',
    description: 'Fresh limes',
    price: 3.99,
    unit: 'per lb',
    category: 'Fruits',
    imageIcon: '🍋',
  ),
  Product(
    id: '50',
    name: 'Avocados',
    description: 'Ripe avocados',
    price: 5.99,
    unit: 'per lb',
    category: 'Fruits',
    imageIcon: '🥑',
  ),

  // Dairy
  Product(
    id: '51',
    name: 'Fresh Milk',
    description: 'Farm fresh whole milk',
    price: 4.49,
    unit: 'per gallon',
    category: 'Dairy',
    imageIcon: '🥛',
  ),
  Product(
    id: '52',
    name: 'Farm Eggs',
    description: 'Free-range chicken eggs',
    price: 6.99,
    unit: 'per dozen',
    category: 'Dairy',
    imageIcon: '🥚',
  ),
  Product(
    id: '53',
    name: 'Fresh Cheese',
    description: 'Artisan farm cheese',
    price: 8.99,
    unit: 'per lb',
    category: 'Dairy',
    imageIcon: '🧀',
  ),
  Product(
    id: '54',
    name: 'Greek Yogurt',
    description: 'Creamy Greek yogurt',
    price: 5.99,
    unit: 'per 32 oz',
    category: 'Dairy',
    imageIcon: '🥛',
  ),
  Product(
    id: '55',
    name: 'Farm Butter',
    description: 'Fresh churned butter',
    price: 6.99,
    unit: 'per lb',
    category: 'Dairy',
    imageIcon: '🧈',
  ),
];
